# This is a basic workflow to help you get started with Actions

name: FirstWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, Dev ]
  pull_request:
    branches: [ master, Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BASE_BRANCH_NAME: 'Dev'
  BASE_BRANCH_SOURCE_FOLD: 'src/main/java/resources/'
  TARGET_BRANCH_NAME: 'master'
  TARGET_BRANCH_DEST_FOLD: 'src/main/java/resources/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: show main enviroment variable(after testing, comment out it.)
        run: |
          echo “::debug::workspace=${{ github.workspace }}”
          echo "::debug::repository=${{ github.repository }}"
          echo "::debug::env=${{ github.env }}"
          echo "::debug::ref=${{ github.ref }}"
          echo "::debug::token=${{ secrets.GITHUB_TOKEN }}"

      - name: check out source branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ env.BASE_BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.BASE_BRANCH_NAME }}

      - name: fetch files in specifiecd path(source branch)
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: ${{ env.BASE_BRANCH_NAME }}/${{ env.BASE_BRANCH_SOURCE_FOLD }}

      - name: check out target branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ env.TARGET_BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.TARGET_BRANCH_NAME }}

      - name: copy file from checked out path of source branch to corresponding path
        run: |
          cd ${{ github.workspace }}
          for i in ${{ steps.pl.outputs.paths }}; do
            cp $i ${{ env.TARGET_BRANCH_NAME }}/${{ env.TARGET_BRANCH_DEST_FOLD }}
          done 

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          # cache: 'maven'

          # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: build with maven
        run: |
          cd ${{ env.TARGET_BRANCH_NAME }}
          mvn clean package -DskipTests=true

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.TARGET_BRANCH_NAME }}/target/aeonpeopleportal-api.jar

